open! Core
open! Import

let map_function_roots ~f functions =
  Map.map ~f:(Function.map_root ~f) functions
;;

let test_cfg s =
  s
  |> Parser.parse_string
  |> Result.map ~f:(map_function_roots ~f:Cfg.process)
  |> function
  | Error e -> Nod_error.to_string e |> print_endline
  | Ok fns ->
    Map.iter
      fns
      ~f:(fun { Function.root = ~root:_, ~blocks:_, ~in_order:blocks; _ } ->
        Vec.iter blocks ~f:(fun block ->
          let instrs =
            Vec.to_list block.Block.instructions @ [ block.terminal ]
          in
          print_s [%message block.id_hum (instrs : Ir.t list)]))
;;

let test_ssa ?don't_opt s =
  test_cfg s;
  print_endline "=================================";
  Parser.parse_string s
  |> Result.map ~f:(map_function_roots ~f:Cfg.process)
  |> Result.map ~f:Eir.set_entry_block_args
  |> Result.map ~f:(map_function_roots ~f:Ssa.create)
  |> function
  | Error e -> Nod_error.to_string e |> print_endline
  | Ok fns ->
    let go fns =
      Map.iter fns ~f:(fun { Function.root = (ssa : Ssa.t); _ } ->
        Vec.iter ssa.in_order ~f:(fun block ->
          let instrs = Vec.to_list block.instructions @ [ block.terminal ] in
          print_s
            [%message
              block.id_hum ~args:(block.args : Var.t Vec.t) (instrs : Ir.t list)]))
    in
    go fns;
    (match don't_opt with
     | Some () -> ()
     | None ->
       print_endline "******************************";
       Eir.optimize fns;
       go fns)
;;

let compile_and_lower ?(opt_flags = Eir.Opt_flags.no_opt) program =
  match Nod.compile ~opt_flags program with
  | Error e -> Nod_error.to_string e |> print_endline
  | Ok functions ->
    let asm = X86_backend.compile_to_asm functions in
    print_endline asm
;;

let borked = Examples.Textual.regalloc_hard

let%expect_test "run" =
  let output = compile_and_execute ~opt_flags:Eir.Opt_flags.no_opt borked in
  print_endline output;
  [%expect.unreachable]
[@@expect.uncaught_exn {|
  (* CR expect_test_collector: This test expectation appears to contain a backtrace.
     This is strongly discouraged as backtraces are fragile.
     Please change this test to not include a backtrace. *)
  ("Want to assign phys reg but already found"
    (a (Reg ((reg RAX) (class_ I64)))) (to_ ((reg R15) (class_ I64))))
  Raised at Base__Error.raise in file "src/error.ml", line 17, characters 38-66
  Called from Base__Error.raise_s in file "src/error.ml" (inlined), line 26, characters 52-76
  Called from Nod_x86_backend__Regalloc.update_assignment.(fun) in file "x86_backend/regalloc.ml", lines 73-77, characters 6-149
  Called from Base__Hashtbl.update_and_return in file "src/hashtbl.ml" (inlined), line 607, characters 13-40
  Called from Base__Hashtbl.update in file "src/hashtbl.ml" (inlined), line 613, characters 17-56
  Called from Nod_x86_backend__Regalloc.update_assignment in file "x86_backend/regalloc.ml", lines 69-77, characters 2-310
  Called from Base__List0.iter in file "src/list0.ml" (inlined), line 83, characters 4-7
  Called from Nod_x86_backend__Regalloc.run_sat.run in file "x86_backend/regalloc.ml" (inlined), lines 199-205, characters 8-323
  Called from Nod_x86_backend__Regalloc.run_sat.run in file "x86_backend/regalloc.ml", lines 199-205, characters 8-323
  Called from Base__List0.iter in file "src/list0.ml" (inlined), line 83, characters 4-7
  Called from Nod_x86_backend__Regalloc.run in file "x86_backend/regalloc.ml", lines 325-333, characters 2-203
  Called from Base__Map.Tree0.map in file "src/map.ml", line 1083, characters 59-62
  Called from Base__Map.Accessors.map in file "src/map.ml" (inlined), line 2522, characters 36-57
  Called from Nod_x86_backend__X86_backend.compile in file "x86_backend/x86_backend.ml", lines 6-7, characters 2-94
  Called from Nod_x86_backend__X86_backend.compile_to_asm in file "x86_backend/x86_backend.ml", line 12, characters 2-30
  Called from Nod.compile_and_execute in file "lib/nod.ml", line 98, characters 14-50
  Called from Nod_debug_test__Test_tmp.(fun) in file "debug_test/test_tmp.ml", line 63, characters 15-73
  Called from Ppx_expect_runtime__Test_block.Configured.dump_backtrace in file "runtime/test_block.ml", line 358, characters 10-25
  |}]
;;

let%expect_test "borked" =
  compile_and_lower ~opt_flags:Eir.Opt_flags.no_opt borked;
  [%expect.unreachable]
[@@expect.uncaught_exn {|
  (* CR expect_test_collector: This test expectation appears to contain a backtrace.
     This is strongly discouraged as backtraces are fragile.
     Please change this test to not include a backtrace. *)
  ("Want to assign phys reg but already found"
    (a (Reg ((reg RAX) (class_ I64)))) (to_ ((reg R15) (class_ I64))))
  Raised at Base__Error.raise in file "src/error.ml", line 17, characters 38-66
  Called from Base__Error.raise_s in file "src/error.ml" (inlined), line 26, characters 52-76
  Called from Nod_x86_backend__Regalloc.update_assignment.(fun) in file "x86_backend/regalloc.ml", lines 73-77, characters 6-149
  Called from Base__Hashtbl.update_and_return in file "src/hashtbl.ml" (inlined), line 607, characters 13-40
  Called from Base__Hashtbl.update in file "src/hashtbl.ml" (inlined), line 613, characters 17-56
  Called from Nod_x86_backend__Regalloc.update_assignment in file "x86_backend/regalloc.ml", lines 69-77, characters 2-310
  Called from Base__List0.iter in file "src/list0.ml" (inlined), line 83, characters 4-7
  Called from Nod_x86_backend__Regalloc.run_sat.run in file "x86_backend/regalloc.ml" (inlined), lines 199-205, characters 8-323
  Called from Nod_x86_backend__Regalloc.run_sat.run in file "x86_backend/regalloc.ml", lines 199-205, characters 8-323
  Called from Base__List0.iter in file "src/list0.ml" (inlined), line 83, characters 4-7
  Called from Nod_x86_backend__Regalloc.run in file "x86_backend/regalloc.ml", lines 325-333, characters 2-203
  Called from Base__Map.Tree0.map in file "src/map.ml", line 1083, characters 59-62
  Called from Base__Map.Accessors.map in file "src/map.ml" (inlined), line 2522, characters 36-57
  Called from Nod_x86_backend__X86_backend.compile in file "x86_backend/x86_backend.ml", lines 6-7, characters 2-94
  Called from Nod_x86_backend__X86_backend.compile_to_asm in file "x86_backend/x86_backend.ml", line 12, characters 2-30
  Called from Nod_debug_test__Test_tmp.compile_and_lower in file "debug_test/test_tmp.ml", line 56, characters 14-50
  Called from Nod_debug_test__Test_tmp.compile_and_lower in file "debug_test/test_tmp.ml" (inlined), lines 52-57, characters 22-261
  Called from Nod_debug_test__Test_tmp.(fun) in file "debug_test/test_tmp.ml", line 95, characters 2-58
  Called from Ppx_expect_runtime__Test_block.Configured.dump_backtrace in file "runtime/test_block.ml", line 358, characters 10-25
  |}]
;;

let%expect_test "debug borked opt ssa" =
  test_ssa ~don't_opt:() borked;
  [%expect
    {|
    (%root
     (instrs
      ((Move ((name a) (type_ I64)) (Lit 1))
       (Move ((name b) (type_ I64)) (Lit 2))
       (Move ((name c) (type_ I64)) (Lit 3))
       (Move ((name d) (type_ I64)) (Lit 4))
       (Move ((name e) (type_ I64)) (Lit 5))
       (Move ((name f) (type_ I64)) (Lit 6))
       (Move ((name g) (type_ I64)) (Lit 7))
       (Move ((name h) (type_ I64)) (Lit 8))
       (Move ((name i) (type_ I64)) (Lit 9))
       (Move ((name j) (type_ I64)) (Lit 10))
       (Move ((name k) (type_ I64)) (Lit 11))
       (Move ((name l) (type_ I64)) (Lit 12))
       (Move ((name m) (type_ I64)) (Lit 13))
       (Add
        ((dest ((name s1) (type_ I64))) (src1 (Var ((name a) (type_ I64))))
         (src2 (Var ((name b) (type_ I64))))))
       (Add
        ((dest ((name s2) (type_ I64))) (src1 (Var ((name s1) (type_ I64))))
         (src2 (Var ((name c) (type_ I64))))))
       (Add
        ((dest ((name s3) (type_ I64))) (src1 (Var ((name s2) (type_ I64))))
         (src2 (Var ((name d) (type_ I64))))))
       (Add
        ((dest ((name s4) (type_ I64))) (src1 (Var ((name s3) (type_ I64))))
         (src2 (Var ((name e) (type_ I64))))))
       (Add
        ((dest ((name s5) (type_ I64))) (src1 (Var ((name s4) (type_ I64))))
         (src2 (Var ((name f) (type_ I64))))))
       (Add
        ((dest ((name s6) (type_ I64))) (src1 (Var ((name s5) (type_ I64))))
         (src2 (Var ((name g) (type_ I64))))))
       (Add
        ((dest ((name s7) (type_ I64))) (src1 (Var ((name s6) (type_ I64))))
         (src2 (Var ((name h) (type_ I64))))))
       (Add
        ((dest ((name s8) (type_ I64))) (src1 (Var ((name s7) (type_ I64))))
         (src2 (Var ((name i) (type_ I64))))))
       (Add
        ((dest ((name s9) (type_ I64))) (src1 (Var ((name s8) (type_ I64))))
         (src2 (Var ((name j) (type_ I64))))))
       (Add
        ((dest ((name s10) (type_ I64))) (src1 (Var ((name s9) (type_ I64))))
         (src2 (Var ((name k) (type_ I64))))))
       (Add
        ((dest ((name s11) (type_ I64))) (src1 (Var ((name s10) (type_ I64))))
         (src2 (Var ((name l) (type_ I64))))))
       (Add
        ((dest ((name s12) (type_ I64))) (src1 (Var ((name s11) (type_ I64))))
         (src2 (Var ((name m) (type_ I64))))))
       (Return (Var ((name s12) (type_ I64)))))))
    =================================
    (%root (args ())
     (instrs
      ((Move ((name a) (type_ I64)) (Lit 1))
       (Move ((name b) (type_ I64)) (Lit 2))
       (Move ((name c) (type_ I64)) (Lit 3))
       (Move ((name d) (type_ I64)) (Lit 4))
       (Move ((name e) (type_ I64)) (Lit 5))
       (Move ((name f) (type_ I64)) (Lit 6))
       (Move ((name g) (type_ I64)) (Lit 7))
       (Move ((name h) (type_ I64)) (Lit 8))
       (Move ((name i) (type_ I64)) (Lit 9))
       (Move ((name j) (type_ I64)) (Lit 10))
       (Move ((name k) (type_ I64)) (Lit 11))
       (Move ((name l) (type_ I64)) (Lit 12))
       (Move ((name m) (type_ I64)) (Lit 13))
       (Add
        ((dest ((name s1) (type_ I64))) (src1 (Var ((name a) (type_ I64))))
         (src2 (Var ((name b) (type_ I64))))))
       (Add
        ((dest ((name s2) (type_ I64))) (src1 (Var ((name s1) (type_ I64))))
         (src2 (Var ((name c) (type_ I64))))))
       (Add
        ((dest ((name s3) (type_ I64))) (src1 (Var ((name s2) (type_ I64))))
         (src2 (Var ((name d) (type_ I64))))))
       (Add
        ((dest ((name s4) (type_ I64))) (src1 (Var ((name s3) (type_ I64))))
         (src2 (Var ((name e) (type_ I64))))))
       (Add
        ((dest ((name s5) (type_ I64))) (src1 (Var ((name s4) (type_ I64))))
         (src2 (Var ((name f) (type_ I64))))))
       (Add
        ((dest ((name s6) (type_ I64))) (src1 (Var ((name s5) (type_ I64))))
         (src2 (Var ((name g) (type_ I64))))))
       (Add
        ((dest ((name s7) (type_ I64))) (src1 (Var ((name s6) (type_ I64))))
         (src2 (Var ((name h) (type_ I64))))))
       (Add
        ((dest ((name s8) (type_ I64))) (src1 (Var ((name s7) (type_ I64))))
         (src2 (Var ((name i) (type_ I64))))))
       (Add
        ((dest ((name s9) (type_ I64))) (src1 (Var ((name s8) (type_ I64))))
         (src2 (Var ((name j) (type_ I64))))))
       (Add
        ((dest ((name s10) (type_ I64))) (src1 (Var ((name s9) (type_ I64))))
         (src2 (Var ((name k) (type_ I64))))))
       (Add
        ((dest ((name s11) (type_ I64))) (src1 (Var ((name s10) (type_ I64))))
         (src2 (Var ((name l) (type_ I64))))))
       (Add
        ((dest ((name s12) (type_ I64))) (src1 (Var ((name s11) (type_ I64))))
         (src2 (Var ((name m) (type_ I64))))))
       (Return (Var ((name s12) (type_ I64)))))))
    |}]
;;

let%expect_test "debug borked" =
  match Nod.compile ~opt_flags:Eir.Opt_flags.no_opt borked with
  | Error e -> Nod_error.to_string e |> print_endline
  | Ok functions ->
    X86_backend.For_testing.print_selected_instructions functions;
    [%expect
      {|
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | block         | instruction                                                                                                                           | live_in                                                                                                                                                                                                                                                                              | live_out                                                                                                                                                                                                                                                                             |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__prologue | (block start(args()))                                                                                                                 | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__prologue | (X86(Tag_def NOOP(Reg((reg RBP)(class_ I64)))))                                                                                       | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__prologue | (X86(JMP((block((id_hum %root)(args())))(args()))))                                                                                   | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__prologue | block end                                                                                                                             | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (block start(args()))                                                                                                                 | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name a)(type_ I64))))(class_ I64)))(Imm 1)))                                                           | {}                                                                                                                                                                                                                                                                                   | (((name a)(type_ I64)))                                                                                                                                                                                                                                                              |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name b)(type_ I64))))(class_ I64)))(Imm 2)))                                                           | (((name a)(type_ I64)))                                                                                                                                                                                                                                                              | (((name a)(type_ I64))((name b)(type_ I64)))                                                                                                                                                                                                                                         |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name c)(type_ I64))))(class_ I64)))(Imm 3)))                                                           | (((name a)(type_ I64))((name b)(type_ I64)))                                                                                                                                                                                                                                         | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64)))                                                                                                                                                                                                                    |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name d)(type_ I64))))(class_ I64)))(Imm 4)))                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64)))                                                                                                                                                                                                                    | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64)))                                                                                                                                                                                               |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name e)(type_ I64))))(class_ I64)))(Imm 5)))                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64)))                                                                                                                                                                                               | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64)))                                                                                                                                                                          |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name f)(type_ I64))))(class_ I64)))(Imm 6)))                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64)))                                                                                                                                                                          | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64)))                                                                                                                                                     |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name g)(type_ I64))))(class_ I64)))(Imm 7)))                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64)))                                                                                                                                                     | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64)))                                                                                                                                |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name h)(type_ I64))))(class_ I64)))(Imm 8)))                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64)))                                                                                                                                | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64)))                                                                                                           |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name i)(type_ I64))))(class_ I64)))(Imm 9)))                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64)))                                                                                                           | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64)))                                                                                      |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name j)(type_ I64))))(class_ I64)))(Imm 10)))                                                          | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64)))                                                                                      | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64)))                                                                 |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name k)(type_ I64))))(class_ I64)))(Imm 11)))                                                          | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64)))                                                                 | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64)))                                            |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name l)(type_ I64))))(class_ I64)))(Imm 12)))                                                          | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64)))                                            | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64)))                       |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name m)(type_ I64))))(class_ I64)))(Imm 13)))                                                          | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64)))                       | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64)))  |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s1)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name a)(type_ I64))))(class_ I64)))))       | (((name a)(type_ I64))((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64)))  | (((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s1)(type_ I64))) |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s1)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name b)(type_ I64))))(class_ I64)))))       | (((name b)(type_ I64))((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s1)(type_ I64))) | (((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s1)(type_ I64)))                      |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s2)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s1)(type_ I64))))(class_ I64)))))      | (((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s1)(type_ I64)))                      | (((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s2)(type_ I64)))                      |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s2)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name c)(type_ I64))))(class_ I64)))))       | (((name c)(type_ I64))((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s2)(type_ I64)))                      | (((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s2)(type_ I64)))                                           |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s3)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s2)(type_ I64))))(class_ I64)))))      | (((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s2)(type_ I64)))                                           | (((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s3)(type_ I64)))                                           |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s3)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name d)(type_ I64))))(class_ I64)))))       | (((name d)(type_ I64))((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s3)(type_ I64)))                                           | (((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s3)(type_ I64)))                                                                |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s4)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s3)(type_ I64))))(class_ I64)))))      | (((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s3)(type_ I64)))                                                                | (((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s4)(type_ I64)))                                                                |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s4)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name e)(type_ I64))))(class_ I64)))))       | (((name e)(type_ I64))((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s4)(type_ I64)))                                                                | (((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s4)(type_ I64)))                                                                                     |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s5)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s4)(type_ I64))))(class_ I64)))))      | (((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s4)(type_ I64)))                                                                                     | (((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s5)(type_ I64)))                                                                                     |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s5)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name f)(type_ I64))))(class_ I64)))))       | (((name f)(type_ I64))((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s5)(type_ I64)))                                                                                     | (((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s5)(type_ I64)))                                                                                                          |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s6)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s5)(type_ I64))))(class_ I64)))))      | (((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s5)(type_ I64)))                                                                                                          | (((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s6)(type_ I64)))                                                                                                          |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s6)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name g)(type_ I64))))(class_ I64)))))       | (((name g)(type_ I64))((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s6)(type_ I64)))                                                                                                          | (((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s6)(type_ I64)))                                                                                                                               |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s7)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s6)(type_ I64))))(class_ I64)))))      | (((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s6)(type_ I64)))                                                                                                                               | (((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s7)(type_ I64)))                                                                                                                               |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s7)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name h)(type_ I64))))(class_ I64)))))       | (((name h)(type_ I64))((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s7)(type_ I64)))                                                                                                                               | (((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s7)(type_ I64)))                                                                                                                                                    |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s8)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s7)(type_ I64))))(class_ I64)))))      | (((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s7)(type_ I64)))                                                                                                                                                    | (((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s8)(type_ I64)))                                                                                                                                                    |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s8)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name i)(type_ I64))))(class_ I64)))))       | (((name i)(type_ I64))((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s8)(type_ I64)))                                                                                                                                                    | (((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s8)(type_ I64)))                                                                                                                                                                         |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s9)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s8)(type_ I64))))(class_ I64)))))      | (((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s8)(type_ I64)))                                                                                                                                                                         | (((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s9)(type_ I64)))                                                                                                                                                                         |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s9)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name j)(type_ I64))))(class_ I64)))))       | (((name j)(type_ I64))((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s9)(type_ I64)))                                                                                                                                                                         | (((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s9)(type_ I64)))                                                                                                                                                                                              |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s10)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s9)(type_ I64))))(class_ I64)))))     | (((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s9)(type_ I64)))                                                                                                                                                                                              | (((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s10)(type_ I64)))                                                                                                                                                                                             |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s10)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name k)(type_ I64))))(class_ I64)))))      | (((name k)(type_ I64))((name l)(type_ I64))((name m)(type_ I64))((name s10)(type_ I64)))                                                                                                                                                                                             | (((name l)(type_ I64))((name m)(type_ I64))((name s10)(type_ I64)))                                                                                                                                                                                                                  |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s11)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s10)(type_ I64))))(class_ I64)))))    | (((name l)(type_ I64))((name m)(type_ I64))((name s10)(type_ I64)))                                                                                                                                                                                                                  | (((name l)(type_ I64))((name m)(type_ I64))((name s11)(type_ I64)))                                                                                                                                                                                                                  |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s11)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name l)(type_ I64))))(class_ I64)))))      | (((name l)(type_ I64))((name m)(type_ I64))((name s11)(type_ I64)))                                                                                                                                                                                                                  | (((name m)(type_ I64))((name s11)(type_ I64)))                                                                                                                                                                                                                                       |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name s12)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s11)(type_ I64))))(class_ I64)))))    | (((name m)(type_ I64))((name s11)(type_ I64)))                                                                                                                                                                                                                                       | (((name m)(type_ I64))((name s12)(type_ I64)))                                                                                                                                                                                                                                       |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(ADD(Reg((reg(Unallocated((name s12)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name m)(type_ I64))))(class_ I64)))))      | (((name m)(type_ I64))((name s12)(type_ I64)))                                                                                                                                                                                                                                       | (((name s12)(type_ I64)))                                                                                                                                                                                                                                                            |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name res__0)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name s12)(type_ I64))))(class_ I64))))) | (((name s12)(type_ I64)))                                                                                                                                                                                                                                                            | (((name s12)(type_ I64)))                                                                                                                                                                                                                                                            |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | (X86_terminal((JMP((block((id_hum sum__epilogue)(args(((name res__0)(type_ I64))))))(args(((name s12)(type_ I64))))))))               | (((name s12)(type_ I64)))                                                                                                                                                                                                                                                            | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | %root         | block end                                                                                                                             | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__epilogue | (block start(args(((name res__0)(type_ I64)))))                                                                                       | {}                                                                                                                                                                                                                                                                                   | (((name res__0)(type_ I64)))                                                                                                                                                                                                                                                         |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__epilogue | (X86(MOV(Reg((reg RAX)(class_ I64)))(Reg((reg(Allocated((name res__0)(type_ I64))(RAX)))(class_ I64)))))                              | (((name res__0)(type_ I64)))                                                                                                                                                                                                                                                         | (((name res__0)(type_ I64)))                                                                                                                                                                                                                                                         |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__epilogue | (X86(RET((Reg((reg(Allocated((name res__0)(type_ I64))(RAX)))(class_ I64))))))                                                        | (((name res__0)(type_ I64)))                                                                                                                                                                                                                                                         | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      | sum__epilogue | block end                                                                                                                             | {}                                                                                                                                                                                                                                                                                   | {}                                                                                                                                                                                                                                                                                   |
      +---------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
      |}]
;;

let%expect_test "debug borked opt" =
  match Nod.compile ~opt_flags:Eir.Opt_flags.default borked with
  | Error e -> Nod_error.to_string e |> print_endline
  | Ok functions ->
    X86_backend.For_testing.print_selected_instructions functions;
    [%expect
      {|
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | block         | instruction                                                                                                                               | live_in                       | live_out                      |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__prologue | (block start(args()))                                                                                                                     | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__prologue | (X86(Tag_def NOOP(Reg((reg RBP)(class_ I64)))))                                                                                           | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__prologue | (X86(JMP((block((id_hum %root)(args())))(args()))))                                                                                       | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__prologue | block end                                                                                                                                 | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | %root         | (block start(args()))                                                                                                                     | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name res__00)(type_ I64))))(class_ I64)))(Imm 91)))                                                        | {}                            | (((name res__00)(type_ I64))) |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | %root         | (X86(MOV(Reg((reg(Unallocated((name res__0)(type_ I64))))(class_ I64)))(Reg((reg(Unallocated((name res__00)(type_ I64))))(class_ I64))))) | (((name res__00)(type_ I64))) | (((name res__00)(type_ I64))) |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | %root         | (X86_terminal((JMP((block((id_hum sum__epilogue)(args(((name res__0)(type_ I64))))))(args(((name res__00)(type_ I64))))))))               | (((name res__00)(type_ I64))) | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | %root         | block end                                                                                                                                 | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__epilogue | (block start(args(((name res__0)(type_ I64)))))                                                                                           | {}                            | (((name res__0)(type_ I64)))  |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__epilogue | (X86(MOV(Reg((reg RAX)(class_ I64)))(Reg((reg(Allocated((name res__0)(type_ I64))(RAX)))(class_ I64)))))                                  | (((name res__0)(type_ I64)))  | (((name res__0)(type_ I64)))  |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__epilogue | (X86(RET((Reg((reg(Allocated((name res__0)(type_ I64))(RAX)))(class_ I64))))))                                                            | (((name res__0)(type_ I64)))  | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      | sum__epilogue | block end                                                                                                                                 | {}                            | {}                            |
      +---------------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-------------------------------+
      |}]
;;
