let max_tuple_arity = 25

let type_var index =
  if index >= 26 then failwith "tuple arity too large";
  Char.chr (Char.code 'a' + index)
;;

let tuple_constructor arity =
  let args =
    List.init arity (fun i -> Printf.sprintf "'%c t" (type_var i))
    |> String.concat " * "
  in
  let tuple =
    List.init arity (fun i -> Printf.sprintf "'%c" (type_var i))
    |> String.concat " * "
  in
  Printf.sprintf "  | Tuple%d : %s -> (%s) t\n" arity args tuple
;;

let tuple_match arity =
  let var index = String.make 1 (type_var index) in
  let args = List.init arity var in
  Printf.sprintf
    "  | Tuple%d (%s) -> Tuple [ %s ]\n"
    arity
    (String.concat ", " args)
    (List.map (fun arg -> "type_ " ^ arg) args |> String.concat "; ")
;;

let type_aliases =
  {|
type base = Dsl_types.base
type record = Dsl_types.record
type int64 = Dsl_types.int64
type float64 = Dsl_types.float64
type ptr = Dsl_types.ptr
|}
;;

let generate_impl () =
  let tuple_defs =
    List.init (max_tuple_arity - 1) (fun i -> tuple_constructor (i + 2))
    |> String.concat ""
  in
  let tuple_matches =
    List.init (max_tuple_arity - 1) (fun i -> tuple_match (i + 2))
    |> String.concat ""
  in
  Printf.printf
    {|(* AUTO-GENERATED by gen_type_repr.ml - do not edit *)
open! Nod_core
open! Dsl_import
%s
type _ t =
  | Int64 : int64 t
  | Float64 : float64 t
  | Ptr : ptr t
%s
let rec type_ : type a. a t -> Type.t =
 fun (type a) (t : a t) : Type.t ->
  match t with
  | Int64 -> I64
  | Float64 -> F64
  | Ptr -> Ptr
%s|}
    type_aliases
    tuple_defs
    tuple_matches
;;

let generate_intf () =
  let tuple_defs =
    List.init (max_tuple_arity - 1) (fun i -> tuple_constructor (i + 2))
    |> String.concat ""
  in
  Printf.printf
    {|(* AUTO-GENERATED by gen_type_repr.ml - do not edit *)
open! Nod_core
open! Dsl_import
%s
type _ t =
  | Int64 : int64 t
  | Float64 : float64 t
  | Ptr : ptr t
%s
val type_ : 'a t -> Type.t
|}
    type_aliases
    tuple_defs
;;

let () =
  match Sys.argv with
  | [| _; "impl" |] -> generate_impl ()
  | [| _; "intf" |] -> generate_intf ()
  | _ ->
    prerr_endline "Usage: ocaml gen_type_repr.ml [impl|intf]";
    exit 1
;;
